### PR TITLE
Phospho data collection scripts

### LINKED ISSUE #2: Identify the right CPTAC data for model fitting

### PR DESCRIPTION
**Pull request by sgosline**
The PDC one doesn't work yet, but the AML data is now run, closes #2 from my end.

### CODE REVIEW

**Comment by sgosline** [comment]
Ok, everything works now - I'm just not sure which data format you prefer @FFroehlich . AML data is tidied, PDC dat ais not.

**Comment by FFroehlich** [comment]
Sorry for the delay here, looks like I don't have access to the `TramData` (https://www.synapse.org/#!Synapse:syn22986341/tables/) or the `CellLinePilotData` (https://www.synapse.org/#!Synapse:syn22255396/tables/)

**Comment by sgosline** [comment]
I think I fixed this - can you confirm you have access?

**Comment by FFroehlich** [comment]
> I think I fixed this - can you confirm you have access?

Yep, works! Thanks!

**Comment by FFroehlich** [comment]
> Ok, everything works now - I'm just not sure which data format you prefer @FFroehlich . AML data is tidied, PDC dat ais not.

Not sure I understand the question. The formatting of the generated `combinePhosphoData.csv` file is perfect on my end, thats the AML data right? Not sure where I can find the PDC data.

**Comment by sgosline** [comment]
What are the rules for merging? @yasharw  will take a look at the correlation analysis using the CPTAC data.

**Pull request merged**
