### PR TITLE
implement pretraining pipeline

### PR DESCRIPTION
**Pull request by FFroehlich**
Adds an implementation for pretraining. With this setup Model training with 10 local starts for the full problem can be done in <1h with 4 local cores and not using parallelization in all steps.

Will add more documentation over the coming days.

### CODE REVIEW

**Comment by FFroehlich** [comment]
This fixes multiple bugs that led to an incorrect formulation of the whole problem. Training for a medium size model (19 proteins, 22 phospho sites) full training runs in 2h on a desktop machine with 4 cores without using parallelization in all steps. 

data: [synthetic__FLT3_MAPK_AKT_STAT.pdf](https://github.com/meyer-lab/mechanismEncoder/files/5625891/synthetic__FLT3_MAPK_AKT_STAT.pdf)


fit: [FLT3_MAPK_AKT_STAT__synthetic__2__fides__fit.pdf](https://github.com/meyer-lab/mechanismEncoder/files/5625890/FLT3_MAPK_AKT_STAT__synthetic__2__fides__fit.pdf)

**Comment by aarmey** [comment]
@FFroehlich I've updated the testing on master to use a self-hosted runner, to get around the env changes with Github Actions. Let me know if you have any difficulties once you merge these changes.

**Comment by FFroehlich** [comment]
> @FFroehlich I've updated the testing on master to use a self-hosted runner, to get around the env changes with Github Actions. Let me know if you have any difficulties once you merge these changes.

Oh sorry, I already fixed everything necessary to adapt to the new env API on GHA, so that wouldn't have been necessary. With the self-hosted runner the individual jobs seem to be queue for quite a while.

**Comment by aarmey** [comment]
Our lab's queue definitely varies from day to day, and is behind today... absolutely feel free to change it back if you'd like.

**Pull request merged**
